function [Rac] = opamp_sim(system,x)

% Create and save the file 'param.cir' to be included in 
% another file to be run by Ngspice.
% The built-in function 'num2str' is used to modify parameters
% wherever it is convenient.
p = ['.param w1=' num2str(x(1)) ' w2=' num2str(x(2))...
    ' w3=' num2str(x(3)) ' w4=' num2str(x(4)) ' w5=' num2str(x(5))...
    ' w6=' num2str(x(6)) ' CL=' num2str(x(7)) ' l1=' num2str(x(8))...
    ' l2=' num2str(x(9)) ' l3=' num2str(x(10)) ' l4=' num2str(x(11))...
    ' l5=' num2str(x(12)) ' l6=' num2str(x(13)) ' Iref=' num2str(x(14))];
dlmwrite('SimInOut/param.cir', p, 'delimiter','');

if system==1
% Run Ngspice
% Make sure Ngspice and .cir files are available 
% in this directory
! C:\Spice64\bin\ngspice -b -o SimOut/opamp-main.out  SimIn/opamp4BsimCard2.cir
! C:\Spice64\bin\ngspice -b -o SimOut/opamp-sr.out    SimIn/opamp4BsimCardslewR.cir
! C:\Spice64\bin\ngspice -b -o simOut/opamp-cmrr.out  SimIn/opamp4BsimCardCMRR.cir
! C:\Spice64\bin\ngspice -b -o SimOut/opamp-psrr.out  SimIn/opamp4BsimCardPSRR.cir
! C:\Spice64\bin\ngspice -b -o SimOut/opamp-psrrn.out SimIn/opamp4BsimCardPSRRN.cir
! C:\Spice64\bin\ngspice -b -o SimOut/opamp-pd.out    SimIn/opamppd.cir

else
% Run Ngspice
% Make sure Ngspice and .cir files are available 
% in this directory
 ! /Applications/ngspice/bin/ngspice -b -o SimOut/opamp-main.out  SimIn/opamp4BsimCard2.cir
 ! /Applications/ngspice/bin/ngspice -b -o SimOut/opamp-sr.out    SimIn/opamp4BsimCardslewR.cir
 ! /Applications/ngspice/bin/ngspice -b -o simOut/opamp-cmrr.out  SimIn/opamp4BsimCardCMRR.cir
 ! /Applications/ngspice/bin/ngspice -b -o SimOut/opamp-psrr.out  SimIn/opamp4BsimCardPSRR.cir
 ! /Applications/ngspice/bin/ngspice -b -o SimOut/opamp-psrrn.out SimIn/opamp4BsimCardPSRRN.cir
 ! /Applications/ngspice/bin/ngspice -b -o SimOut/opamp-pd.out    SimIn/opamppd.cir

end
% Read data saved in .csv files
% (assuming name termination _ac_out.csv)
% Read csv files generated by a 'write' in a 'WNgspiceBaseFile' (.cir file)
% Rac{1} = Frequency Points
% Rac{2} = AC response 
ac = fopen(['SimInOut/ngspice' '.data']);
Rac = textscan(ac,'%f %f %f %f','delimiter','','headerLines',0);
fclose('all');

end
